### ISSUE TITLE
[bug] cloud-build-local always pushes to GCR

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/cloud-build-local#100]
**Platform:**
macOS Mojave: 10.14.5
cloud-build-local Version: v0.5.0
go version: go1.12.5 darwin/amd64

**Issue:**

When running cloud-build-local with both a custom config location and substitutions passed in, the resulting image always gets pushed up to GCR instead of staying local (no --push parameter needed...)

**Final docker image push step in cloudbuild_production.yaml:**

``- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/xxxx:$COMMIT_SHA']
  timeout: 600s``

**Cloud-build-local command being run:**

``cloud-build-local --config=./cloudbuild_production.yaml --dryrun=false --substitutions COMMIT_SHA="local-build-do-no-deploy" .``

**Result:**
Image pushed from local to GCR (e.g. xxxx:local-build-do-no-deploy in this example)

**Expected:**
As the cloud-build-local has no "--push" flag passed to it, no image should be pushed to GCR.

The official documentation (https://cloud.google.com/cloud-build/docs/build-debug-locally) suggests that the built image should **only** be pushed to GCR if the --push flag is used, which is not the case here.

![image](https://user-images.githubusercontent.com/31742730/58393694-a1835f80-7ff4-11e9-8509-b591c7329800.png)

**Comment by codrienne** [comment]
Thanks for filing an issue. An initial glance at the code doesn't reveal any glaring errors, but I've filed a bug internally.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
