### ISSUE TITLE
Add CLI toggle to provide $PROJECT_ID

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloud-build-local#101]
Currently we use the default `gcloud` project that is being used.
Please add a toggle to be able to override.

**Comment by codrienne** [comment]
Can you clarify? You can use the gcloud-wide`--project` flag to override it.

```
gcloud --project=$PROJECT_ID builds submit --config=cloudbuild.yaml .
```

**Comment by hazcod** [comment]
I am using `cloud-build-local`, am I missing something here?

**Comment by neomantra** [comment]
@hazcod I think `$PROJECT_ID` is set to whatever your current environiment's gcloud project is.  So you would have to do `gcloud config set project <my-project>`  to change what project it picks up.

**Comment by sfujiwara** [comment]
Hi, why does this issue is closed?
I think it is useful to specify `$PROJECT_ID` with `cloud-build-local`.

When we are using multiple project (for example {dev, stg, prod}), making developers to execute `gcloud config set project` might be a cause of a human error.
