### ISSUE TITLE
Cloud Build Local errors when substitutions are not matched in the template

### ISSUE THREAD

**Issue by jonstacks** [GoogleCloudPlatform/cloud-build-local#102]
We are having an issue that works in google Cloud Build, but not with cloud-build-local. We are defining 2 substitution keys `_STATUSES` and `_SLACK_WEBHOOK_URL` that are not used in the template `steps`. We set these substitutions for use in a cloud function that subscribes to cloud build to have finer grain control on which slack channel we send notifications to and for which build statuses we send notifications. 

Here is the error we are getting:

```
2019/07/09 09:43:40 Error merging substitutions and validating build: Error validating build: key "_SLACK_WEBHOOK_URL" in the substitution data is not matched in the template;key "_STATUSES" in the substitution data is not matched in the template
make: *** [local-cloud-build] Error 1
```

Would it be possible to update the validation rules on cloud-build-local to more closely match the functionality in Cloud Build?

**Comment by Philmod** [comment]
Have you tried to use the build option `ALLOW_LOOSE`? https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/validate/validate.go#L129

**Comment by jonstacks** [comment]
🤦‍♂ 

@Philmod, thank you! Just tried that and it worked locally now. Not sure why it was working in GCB, but it is there in the docs saying I should use it. Thanks again.
