### ISSUE TITLE
Error copying source to docker volume: exit status 1

### ISSUE THREAD

**Issue by HalfdanJ** [GoogleCloudPlatform/cloud-build-local#104]
I'm not able to run cloud-build-local on a project that run without issues in cloud build. 

If i do a dry run it runs successfully, but when turning off dry run i get following error:

```
▶ cloud-build-local --config cloudbuild.yml  --dryrun=false .    
2019/09/06 09:56:24 Warning: there are left over step containers from a previous build, cleaning them.
2019/09/06 09:56:24 Warning: there are left over step volumes from a previous build, cleaning it.
2019/09/06 09:56:24 Warning: The server docker version installed (19.03.1) is different from the one used in GCB (18.09.0)
2019/09/06 09:56:24 Warning: The client docker version installed (19.03.1) is different from the one used in GCB (18.09.0)
2019/09/06 09:56:36 Error copying source to docker volume: exit status 1
```

I'm running it on mac. Is this due to too new version of docker?

**Comment by AdamNowotny** [comment]
Having a similar issue, but with code 127 after upgrade to Linux Fedora 31:
```
2019/10/30 15:49:09 Warning: there are left over step containers from a previous build, cleaning them.
2019/10/30 15:49:09 Warning: there are left over step volumes from a previous build, cleaning it.
2019/10/30 15:49:09 Warning: The server docker version installed (19.03.4) is different from the one used in GCB (18.09.0)
2019/10/30 15:49:09 Warning: The client docker version installed (19.03.4) is different from the one used in GCB (18.09.0)
2019/10/30 15:49:13 Error copying source to docker volume: exit status 127
```

**Comment by kiratp** [comment]
I ran into this and figured out the problem.

The issue occurs when docker cp fails here https://github.com/GoogleCloudPlatform/cloud-build-local/blob/9b7cb6f1ce936e350695c6da42ad5fc6f4a8fa8c/volume/volume.go#L79

Do the following: 

`docker container ls`

There should be a container that has some name starting cloudbuild_

Try the following in your source directory, replacing SRC_
`docker cp . $CONTAINER_ID:/workspace`

This command will probably fail but the error message will tell you what went wrong. 

In my case it was a bad symlink inside a UX design tool's node_modules directory.

**Comment by hilnius** [comment]
For whoever has the same issue, for me the error was caused by a folder from which I was executing `cloud-build-local` that was not owned by myself but another user.
`sudo chown -R myself:myself .` in the folder from which I was executing `cloud-build-local` solved it.

**Comment by gregmartyn** [comment]
> Do the following:
> docker container ls

I had to do `docker container ls -a` to find it, but sure enough, `docker cp . $CONTAINER_ID:/workspace` told me exactly which file was erroring. Thanks!

**Comment by akauppi** [comment]
Having this. My build config is under `builds` and doing the `docker cp` simply does not return:

```
$ cd builds
$ docker cp .. $CONTAINER_ID:/workspace
```

**Comment by akauppi** [comment]
What solved the problem for me:

I am using a custom builder and used a `USER` command in its `Dockerfile` (since I normally think it's a good practise). With Cloud Build, this causes all kinds of access problems. After running as `root`, also the `cloud-build-local` started working.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
