### ISSUE TITLE
Different results with cloud-build-local than with gcloud builds submit: Surely wrong?

### ISSUE THREAD

**Issue by joelbernstein** [GoogleCloudPlatform/cloud-build-local#107]
I presume that invoking cloud-build-local something like:
`cloud-build-local --config deploy/cloudbuild.yaml --substitutions=BRANCH_NAME=master,SHORT_SHA=blahblah -dryrun=false -write-workspace=/tmp/workspace .`

would be equivalent to a cloud build involved like:
`gcloud builds submit --config deploy/cloudbuild.yaml --substitutions=BRANCH_NAME=master,SHORT_SHA=blahblah`

Is this assumption invalid? Exactly how are they meant to differ? The issue is that the exact same codebase and cloudbuild.yaml are producing different build output (one passes tests, the other fails). Consistently so.

**Comment by joelbernstein** [comment]
Is it possible that something left behind in the `workspace` would be affecting the next run?

To be clear (as I can without showing lots of proprietary code) I am using cloudbuild to invoke docker-compose to build and test some code. Tests also run via docker. Tests are failing in _local_ builds but always succeed in _remote_ builds. Any tips on how to dig for this are gratefully accepted.

**Comment by joelbernstein** [comment]
Ha, I think this _was_ related to build artifacts remaining in a (reused) workspace.

Having run my cloud-build-local command with -write-workspace=/tmp/somewhereelse i got a successful build.

What a ridiculous bug. Why would this be desirable?

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
