### ISSUE TITLE
Substitution Limits Different Between Local and Cloud

### ISSUE THREAD

**Issue by neomantra** [GoogleCloudPlatform/cloud-build-local#108]
I have a build that works fine on Cloud Build, but fails on  `cloud-build-local`

It is the `maxSubstValueLength` limit that I'm hitting.   The Cloud Build has one substitution value that is ~4400 bytes and works fine.

Can these be validation limits be updated to be closer to what Cloud Build allows? 

https://github.com/GoogleCloudPlatform/cloud-build-local/blob/f3e20a846128abfe7debe952dfec457460f7ef6a/validate/validate.go#L54

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
