### ISSUE TITLE
command not found: cloud-build-local Post-Installation

### ISSUE THREAD

**Issue by ShawnConn** [GoogleCloudPlatform/cloud-build-local#112]
After running `gcloud components install cloud-build-local` the bin path isn't added to the shell's path var. 

Upon some inspection, I did find the installed location (`/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/cloud-build-local`). However, running a local build with the [GCP quickstart example](https://github.com/GoogleCloudBuild/code-examples/blob/master/quickstart-build/cloudbuild.yaml) looks to fail:

```
2020/03/25 16:09:17 RUNNER - [docker ps -a -q --filter name=step_[0-9]+|cloudbuild_|metadata]
2020/03/25 16:09:17 RUNNER - [docker network ls -q --filter name=cloudbuild]
2020/03/25 16:09:17 RUNNER - [docker volume ls -q --filter name=homevol|cloudbuild_]
2020/03/25 16:09:18 Build id = localbuild_620c483d-6580-4f56-88a1-1cca76369239
2020/03/25 16:09:18 RUNNER - [docker volume create --name homevol]
2020/03/25 16:09:18 status changed to "BUILD"
BUILD
2020/03/25 16:09:18 RUNNER - [docker inspect gcr.io/cloud-builders/docker]
: Already have image: gcr.io/cloud-builders/docker
2020/03/25 16:09:18 RUNNER - [docker run --rm --name step_0 --volume /var/run/docker.sock:/var/run/docker.sock --privileged --volume cloudbuild_vol_04b922ce-0746-4d6d-9a2a-4924dd191cb6:/workspace --workdir /workspace --volume homevol:/builder/home --env HOME=/builder/home --network cloudbuild --volume /tmp/step-0/:/builder/outputs --env BUILDER_OUTPUT=/builder/outputs gcr.io/cloud-builders/docker build -t gcr.io/luciditi/project .]
2020/03/25 16:09:18 Step  finished
2020/03/25 16:09:18 RUNNER - [docker images -q gcr.io/luciditi/project]
2020/03/25 16:09:18 RUNNER - [docker rm -f step_0]
2020/03/25 16:09:18 status changed to "ERROR"
ERROR
ERROR: failed to find one or more images after execution of build steps: ["gcr.io/luciditi/project"]
2020/03/25 16:09:18 RUNNER - [docker volume rm homevol]
2020/03/25 16:09:18 Build finished with ERROR status
```

- OS: macOS 10.15.3
- Docker Version: 2.2.0.4 (43472)

**Comment by ShawnConn** [comment]
For anyone with this issue, it can be solved by following the instructions for installing via Go, as noted on the [contribution steps](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/CONTRIBUTING.md).

**Comment by alexisagos** [comment]
Have a look at this [gist,](https://gist.github.com/dwchiang/10849350) after running this command:
`source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"`
It worked for me ! Replace `bash` in the command with `zsh` or `fish` to match your needs.

**Comment by d3f2** [comment]
As @alexisagos said note that you need to run both these commands (zsh shell example):
```
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
```

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
