### ISSUE TITLE
Substitution in logsBucket is not picked up - cloud-build-local errors out?

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/cloud-build-local#114]
I have a substitution in my yaml config for logsBucket that looks like this:

```yaml
logsBucket: '$_LOGS_BUCKET'
```

But cloud-build-local throws an error: Error merging substitutions and validating build: Error validating build: key "_LOGS_BUCKET" in the substitution data is not matched in the template.

**Comment by ejose19** [comment]
Same issue with `options.env`, substitutions there are not being considered and build errors out with the same error you get.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
