### ISSUE TITLE
cloud-build-local ignores DOCKER_HOST environment variable

### ISSUE THREAD

**Issue by SanjayVas** [GoogleCloudPlatform/cloud-build-local#116]
Instead of using the `DOCKER_HOST` environment variable, cloud-build-local appears to have the default Unix socket path (`/var/run/docker.sock`) hard-coded.

See https://github.com/GoogleCloudPlatform/cloud-build-local/blob/9b7cb6f1ce936e350695c6da42ad5fc6f4a8fa8c/build/build.go#L467-L468

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
