### ISSUE TITLE
errors with successful build

### ISSUE THREAD

**Issue by matti** [GoogleCloudPlatform/cloud-build-local#117]
Finished Step #1 - "gbuild2"
2020/07/07 12:53:18 Step Step #1 - "gbuild2" finished
2020/07/07 12:53:18 status changed to "DONE"
DONE
2020/07/07 12:53:18 Error updating docker credentials: failed to update docker credentials: signal: killed
2020/07/07 12:53:18 Failed to delete homevol: exit status 1

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
