### ISSUE TITLE
Error when using comma in substitution key value pair

### ISSUE THREAD

**Issue by znorris** [GoogleCloudPlatform/cloud-build-local#119]
Example command:
`cloud-build-local --dryrun=true --substitutions _CLOUDSDK_COMPUTE_REGION=us-central1,_CLOUDSDK_CONTAINER_CLUSTER=cluster-2,_SKAFFOLD_PROFILES=cluster-2,staging,secrets-staging .`

Error:
```
2020/07/20 10:23:36 RUNNER - [docker ps -a -q --filter name=step_[0-9]+|cloudbuild_|metadata]
2020/07/20 10:23:36 RUNNER - [docker network ls -q --filter name=cloudbuild]
2020/07/20 10:23:36 RUNNER - [docker volume ls -q --filter name=homevol|cloudbuild_]
2020/07/20 10:23:38 Error parsing substitutions flag: The substitution key value pair is not valid: staging
```

Notes:
This is how I run skaffold pipelines via Google Cloud Build triggers. In order for me to test those same pipelines locally I would need to be capable of including a comma in the value. So far various quoting and escaping I've tried hasn't helped.

Similar to #78

**Comment by znorris** [comment]
Those looking for a work-around to pass complex values via the command line may add or edit the `substitutions` key in their `cloudbuild.yaml` as seen in the documentation https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions.

**Comment by jfedgar** [comment]
I worked around this by changing the substitution delimiter from a comma to a semicolon:

`--substitutions=^;^_SOME_KEY=value;_SOME_OTHER_KEY=some_other,value`

see `gcloud topic escaping`

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
