### ISSUE TITLE
Building without access to GCP credentials

### ISSUE THREAD

**Issue by mik-laj** [GoogleCloudPlatform/cloud-build-local#122]
Hello,

I would like to make a feature request to add the ability to build in an environment that does not have GCP access. In my project, we use two CI systems:
- Github Action for development, because it has great integration with Github and is the most developer-friendly.
- Cloud Build for production - build a Docker image, because it ensures audibility and is easy to integrate with IAM.

We want to test the image build on CI as well, so I tried to use this project to run the Cloud Build pipeline on Github Action but unfortunely the GCP project permissions are needed. Our entire process of them does not need access to GCP, so it would be useful to be able to disable the metaserver so that the process could be done fully locally

For now, I have workaround (described below), but the built-in options might help others.

To use this tool without the GCP project, I created the `/scripts/airflow-docker-image/mock_gcloud/gcloud` script.
```bash
#!/usr/bin/env bash

if [[ "$#" -eq 0 ]]; then
    echo "You must provide at arguments."
    exit 1
fi

if [[ "$*" == "config config-helper --format=json" ]]; then
TOKEN_EXPIRE_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ' -d "+1 hour")

cat <<EOF
{
  "configuration": {
    "active_configuration": "default",
    "properties": {
      "core": {
        "account": "ACCOUNT_NAME@example.org",
        "disable_usage_reporting": "False",
        "log_http": "true",
        "project": "project-id"
      }
    }
  },
  "credential": {
    "access_token": "ACCESS_TOKEN",
    "id_token": "ID_TOKEN",
    "token_expiry": "${TOKEN_EXPIRE_DATE}"
  }
}
EOF
echo
    exit 0
fi

if [[ "$*" == "config list --format value(core.project)" ]]; then
    echo "project-id"
    exit 0
fi

if [[ "$*" == "projects describe project-id --format value(projectNumber)" ]]; then
    echo "12345678"
    exit 0
fi

echo "Unsupported command:"
echo "$*"
exit 1
```
and then run the build process as follows:
```
export PATH="$PWD/scripts/airflow-docker-image/mock_gcloud:$PATH"
cloud-build-local --config=scripts/airflow-docker-image/cloudbuild.yaml --dryrun=false .
```

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
