### ISSUE TITLE
Intermittent spoofed metadata server issues

### ISSUE THREAD

**Issue by thealmightygrant** [GoogleCloudPlatform/cloud-build-local#125]
I seem to be seeing an issue where sometimes the spoofed metadata server will not start. It seems as if [this check](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/c7d311b3e2316ec073e3db9394e3a2d874b43e4a/localbuilder_main.go#L212-L216) is the issue. I am on the latest build of `cloud-build-local: 313.0.0`. As far as I can tell, the issue seems to be that somehow [this check](https://github.com/googleapis/google-cloud-go/blob/bd56b2a97e4a7d115510c88316de6e82042860a5/compute/metadata/metadata.go#L117-L182) is succeeding. Interestingly, when I run curl against this address and it does not immediately error out that will be an instance when the spoofed metadata server does not start. I am guessing that somehow I am able to access this server from being logged into GCP, and that this is causing my machine to think that it is running on GCE...

**Comment by thealmightygrant** [comment]
I think what I have discovered is that that this is somehow connected with my VPN for my company that is running on GCP...my guess is that the metadata server is somehow addressable from within the VPN...turning it off seems to allow for this to work every time.

**Comment by bendory** [comment]
Not going to fix this for "special cases" like "my company's VPN is run on GCP."

**Comment by thealmightygrant** [comment]
How is that a special case? Is this not a product of GCP? Who are you trying to serve with this product? I very much doubt that we are the only company dealing with this.
