### ISSUE TITLE
Docker layer progress not displayed

### ISSUE THREAD

**Issue by phil-bee** [GoogleCloudPlatform/cloud-build-local#128]
cloud-build-local    Version: v0.5.2

Cloud-build-local does not show the progress bar when downloading layers within Docker. This means that for the first time, it appears that cloud-build-local has frozen. 

Here is the example output from cloud-build-local:
```Starting Step #2
Step #2: Pulling image: gcr.io/cloud-builders/gcloud
Step #2: Using default tag: latest
Step #2: latest: Pulling from cloud-builders/gcloud
Step #2: 75f546e73d8b: Already exists
Step #2: 0f3bb76fc390: Already exists
Step #2: 3c2cba919283: Already exists
Step #2: b2196a5a20d1: Pulling fs layer
Step #2: dd8547ee0e52:
Step #2: Pulling fs layer
Step #2: 2b11efe6c1f1: Pulling fs layer
Step #2: 17b4726867d5: Pulling fs layer
Step #2: 17b4726867d5: Waiting
Step #2: dd8547ee0e52: Download complete
Step #2: 2b11efe6c1f1: Download complete
```

The process looks like it has hung here but actually it is downloading the layers in the background.

When pulling the same image using Docker, we get:
```docker pull gcr.io/cloud-builders/gcloud
Using default tag: latest
latest: Pulling from cloud-builders/gcloud
75f546e73d8b: Already exists
0f3bb76fc390: Already exists
3c2cba919283: Already exists
b2196a5a20d1: Downloading [=========================================>         ]  440.2MB/535.7MB
dd8547ee0e52: Download complete
2b11efe6c1f1: Download complete
17b4726867d5: Downloading [===========================>                       ]  444.7MB/794.2MB
```

This is much more informative and tells the user that the process hasn't frozen. Could we adapt cloud-build-local so that it displays the download process bars?

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
