### ISSUE TITLE
[bug] inline scripts in `steps[].args` fail validation if env var is not a substitution

### ISSUE THREAD

**Issue by estroz** [GoogleCloudPlatform/cloud-build-local#129]
Given the following `cloudbuild.yaml`:

```yaml
steps:
- name: ubuntu
  env:
  - "FOO=bar"
  entrypoint: "bash"
  args:
  - "-c"
  - |-
    echo $FOO
```

When I run `cloud-build-local` I see the following error:
```console
$ cloud-build-local --config=cloudbuild.yaml --dryrun=false --write-workspace=. .
...
2021/01/14 13:18:45 Error merging substitutions and validating build: Error validating build: key in the template "FOO" is not a valid built-in substitution
```

This error seems to result from not considering defined environment variables during the [`args` substitution check](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/validate/validate.go#L246-L250). The current workaround is to move `echo $FOO` to a script file.

**Comment by ffernandezcast** [comment]
Did you try using $${FOO} I have a similar issue and this one works @estroz

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
