### ISSUE TITLE
Weird maven output

### ISSUE THREAD

**Issue by ricsipontaz** [GoogleCloudPlatform/cloud-build-local#130]
The maven output looks really weird in cloud-build-local:

`Step #1 - "mvn": 2021-02-23 12:59:25,606  INFO --- [                     main] .r.c.s.a.t.ReceiverAccessTokenAuthenticationFilter : Begin filter [/trade-finished]...
Step #1 - "mvn": 2021-02-23 12:59:25,618  INFO --- [             
Step #1 - "mvn":       
Step #1 - "mvn":                                                                                                                                                           Step #1 - "mvn": ma                                                                                                                                                        Step #1 - "mvn": in                                                                                                                                                        Step #1 - "mvn": ]                                                                                                                                                         Step #1 - "mvn":  .r.c.                                                                                                                                                    Step #1 - "mvn": s                                                                                                                                                         
Step #1 - "mvn": .a                                                                                                                                                        Step #1 - "mvn": .t                                                                                                                                                        Step #1 - "mvn": .Re                                                                                                                                                       Step #1 - "mvn": ceiv                                                                                                                                                      
Step #1 - "mvn": er                                                                                                                                                        Step #1 - "mvn": Ac                                                                                                                                                        Step #1 - "mvn": ce                                                                                                                                                        Step #1 - "mvn": ssT                                                                                                                                                       Step #1 - "mvn": oken                                                                                                                                                      Step #1 - "mvn": Au                                                                                                                                                        Step #1 - "mvn": t                                                                                                                                                         Step #1 - "mvn": he                                                                                                                                                        Step #1 - "mvn": nt                                                                                                                                                        Step #1 - "mvn": i                                                                                                                                                         Step #1 - "mvn": ca                                                                  
Step #1 - "mvn": t                                                                                                                                                         
Step #1 - "mvn": io
Step #1 - "mvn": nF
Step #1 - "mvn": il
Step #1 - "mvn": te
Step #1 - "mvn": r 
Step #1 - "mvn": : 
Step #1 - "mvn": En
Step #1 - "mvn": d 
Step #1 - "mvn": f
Step #1 - "mvn": ilte
Step #1 - "mvn": r [/tra
`
But it works as expected on Google Cloud Build.

cloudbuild.yml:
`  - name: 'eu.gcr.io/$PROJECT_ID/compose-mvn-jdk11:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
         && mvn -DargLine="-Dspring.profiles.active=test" clean verify \
        && mvn sonar:sonar \
        && ./build-docker-images.sh \
        && ./upload-docker-images.sh commit`

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
