### ISSUE TITLE
Feature Request: Ability to run specific steps out from cloudbuild.yaml

### ISSUE THREAD

**Issue by timorkal** [GoogleCloudPlatform/cloud-build-local#131]
Hello,

I think it will be very useful to have the ability to run specific steps from the cloudbuild.yml file.
Currently I need to comment and uncomment each time I would like to test a new step I write or to debug the previous ones.

Thanks,

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
