### ISSUE TITLE
Support for `availableSecrets`

### ISSUE THREAD

**Issue by ianks** [GoogleCloudPlatform/cloud-build-local#132]
Currently, the build fails when attempting to run locally:

```
Error loading config file: unknown field "availableSecrets" in cloudbuild.Build
```

**Comment by spy4x** [comment]
Any updates on this?

**Comment by MXWest** [comment]
I"m curious to know if there's some inherent difficulty in adding this support.

**Comment by ekovacs** [comment]
any news on this?

**Comment by VikiAnn** [comment]
Uhhhh this is still pretty necessary for builds with secrets, sooo... any updates?

**Comment by Lizzardd** [comment]
Without this it's rather a pain to test local builds and you're skipping pulling the secret all together

**Comment by bendory** [comment]
Unfortunately we have no plans at this time to add functionality to the Google Cloud Build Local Builder.  We realize that not having this functionality is hindering the local build experience and welcome community contributions to enhance the tool.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
