### ISSUE TITLE
Substitutions blank error

### ISSUE THREAD

**Issue by cameronridderikhoff-teck** [GoogleCloudPlatform/cloud-build-local#133]
When running a build, if the --substitutions flag ends with a comma as in:
`cloud-build-local --substitutions=_FOO="abc",_BAR="efg",`
The error produced is:
`2021/06/28 10:45:49 Error parsing substitutions flag: The substitution key value pair is not valid: `
Which is hard to debug, since the error is not saying that the problem is a trailing comma, but that a specific key-value pair is causing issues. 

As a newcomer to cloud-build-local, I struggled to figure out what was going wrong with my build until I came across someone else's issue posted here, which showed an actual key-value pair in the error.

More documentation on substitutions would help, specifically around syntax on this page [Substitutions](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values)

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
