### ISSUE TITLE
add option to keep volumes created during build

### ISSUE THREAD

**Issue by adrian-gierakowski** [GoogleCloudPlatform/cloud-build-local#134]
To allow users to inspect the content of the volume after the build has finished for debugging purposes.

Ideally we could either keep all volumes or just the ones listed by the user

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
