### ISSUE TITLE
Support for Artifact Registry

### ISSUE THREAD

**Issue by shabutora** [GoogleCloudPlatform/cloud-build-local#135]
We would like to see support for the Artifact Registry as well, as it currently only supports GCR. 
Artifact Registry's URL is [location](https://cloud.google.com/artifact-registry/docs/repo-locations) + `-docker.pkg.dev`.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
