### ISSUE TITLE
provide a darwin-aarch64 build (for MacOs with M1 CPU)

### ISSUE THREAD

**Issue by adrian-gierakowski** [GoogleCloudPlatform/cloud-build-local#136]
can't find one here: https://storage.googleapis.com/local-builder

thanks!

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
