### ISSUE TITLE
support to use podman 

### ISSUE THREAD

**Issue by Raffaello** [GoogleCloudPlatform/cloud-build-local#137]
Hi,

it looks like is not possible to use podman instead of docker for local builds.

Would be a nice addition as an alternative docker option.

**Comment by bendory** [comment]
Close PR as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
