### ISSUE TITLE
Running multiple builds at once errors on docker network creation

### ISSUE THREAD

**Issue by timfallmk** [GoogleCloudPlatform/cloud-build-local#32]
We run multiple parallel builds of images in our project simultaneously in Google Cloud Builder, which works just fine. However, when running locally with the container builder, the creation of a named docker network (`cloudbuild`) causes collisions when attempting to run multiple builds at the same time. The builder errors out when attempting to create the network when it already exists from another process.

Here's an example. This build is being orchestrated by calling `make`.
```Tims-MacBook-Pro-15:management-api timfall$ make update-projects
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j 100 all
cd /Users/timfall/Code/mission-control/auth && \
		container-builder-local --push=false --dryrun=false \
			--config=/Users/timfall/Code/mission-control/cloud-builder/dev.yaml \
			--substitutions="_PROJECT=auth,_CONTEXT_HASH=$(md5 -r dockerfile/base.dockerfile | awk '{ print $1 }')" \
			.
cd /Users/timfall/Code/mission-control/management-api && \
		container-builder-local --push=false --dryrun=false \
			--config=/Users/timfall/Code/mission-control/cloud-builder/dev.yaml \
			--substitutions="_PROJECT=management-api,_CONTEXT_HASH=$(md5 -r dockerfile/base.dockerfile | awk '{ print $1 }')" \
			.
cd /Users/timfall/Code/mission-control/dashboard && \
		container-builder-local --push=false --dryrun=false \
			--config=/Users/timfall/Code/mission-control/cloud-builder/dev.yaml \
			--substitutions="_PROJECT=dashboard,_CONTEXT_HASH=$(md5 -r dockerfile/base.dockerfile | awk '{ print $1 }')" \
			.
cd /Users/timfall/Code/mission-control/dev-tools && \
		container-builder-local --push=false --dryrun=false \
			--config=/Users/timfall/Code/mission-control/cloud-builder/dev.yaml \
			--substitutions="_PROJECT=dev-tools,_CONTEXT_HASH=$(md5 -r dockerfile/base.dockerfile | awk '{ print $1 }')" \
			.
cd /Users/timfall/Code/mission-control/mirror && \
		container-builder-local --push=false --dryrun=false \
			--config=/Users/timfall/Code/mission-control/cloud-builder/dev.yaml \
			--substitutions="_PROJECT=mirror,_CONTEXT_HASH=$(md5 -r dockerfile/base.dockerfile | awk '{ print $1 }')" \
			.
2017/09/19 16:40:27 Warning: The server docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The client docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The server docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The server docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The server docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The client docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The client docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The client docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The server docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
2017/09/19 16:40:27 Warning: The client docker version installed (17.09.0-ce-rc2) is different from the one used in GCB (17.05-ce)
Error response from daemon: network with name cloudbuild already exists
2017/09/19 16:40:32 Failed to start spoofed metadata server: Error creating network: exit status 1
make[1]: *** [build-dev-tools] Error 1
make[1]: *** Waiting for unfinished jobs....
Error response from daemon: network with name cloudbuild already exists
Error response from daemon: network with name cloudbuild already exists
2017/09/19 16:40:32 Failed to start spoofed metadata server: Error creating network: exit status 1
make[1]: *** [build-auth] Error 1
2017/09/19 16:40:32 Failed to start spoofed metadata server: Error creating network: exit status 1
make[1]: *** [build-mirror] Error 1
Error response from daemon: network with name cloudbuild already exists
2017/09/19 16:40:33 Failed to start spoofed metadata server: Error creating network: exit status 1
make[1]: *** [build-dashboard] Error 1
2017/09/19 16:40:33 Started spoofed metadata server
2017/09/19 16:40:37 status changed to "BUILD"
^Cmake[1]: *** [build-management-api] Interrupt: 2
make: *** [update-projects] Interrupt: 2
```
I assume the creation of the docker network is to (somewhat) mimic what happens with specific networks on the cloud side. Perhaps a fix would be to use generated network names for each process? It could also block (or attach to) the `cloudbuild` network if it detects that it already exists?

**Comment by timfallmk** [comment]
Sorry, I should add that we can "fix" this by serializing our builds when done locally, but it would be nice if the local builder were able to operate in parallel processes.

**Comment by Philmod** [comment]
Hey @timfallmk, this is a known [limitation](https://github.com/GoogleCloudPlatform/container-builder-local#limitations) for the moment. Could you tell us more about your use case to run builds in parallel locally?

**Comment by timfallmk** [comment]
@Philmod Sorry, missed that in the limitations section. 

Our parallelization is pretty straightforward actually. We maintain a number of project components in different repos, each one needing to have an image built, tagged, and pushed to our grc.io repo in order to deploy a kubernetes cluster with a given development version. We _could_ go to each repo and run the build command individually, but it was easier to simply templatize a single command in a make file (which does things like calculate the hash, check if new versions of particular projects have been updated, tests passed, etc.) then submits all those builds with the correctly dereferenced variables.

Normally this is submitted to Google Cloud Builder directly, which runs all the different builds separately and in parallel, combining the output for each into the returned log stream. This is perfect for what we want and doesn't depend on local hardware for the repeated dev builds we have to do. Pretty much all the reasons one would use Google Cloud Builder.

I've been trying to debug some caching weirdness with the online builder, and have been using the local builder to do so. Since parity with the online builder is probably an important aspect of the local builder, it might be enough motivation to address this limitation by itself. For practical reasons, we do have occasional development scenarios where we want to do that same thing we _normally_ do (i.e. submit builds to Google Cloud Builder), but are not online for whatever reason. If that works, I have also considered making the local builder an option for some of our deployments that are offline as well.

Hopefully that gives you some idea of the reasons we're using the tool this way. As for Docker networking, I know that can be a pain to navigate, but I'm happy to make suggestions (or a PR) with ideas of how to make the builds process independent.

**Comment by Philmod** [comment]
Hey! The first goal of the local builder was to iterate quickly on a `cloudbuild.yaml`, but we are happy to see new usage.

There are 2 things to consider to make it work concurrently: 
1. Use different volume and network names on each run.
2. Do not [clean](https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/localbuilder_main.go#L119) all the existing volumes / networks / containers on starting (or protect this cleaning with a flag).

These problems don't appear on the online builder as every build uses a fresh and different VM.

Could you tell me more about the "caching weirdness" you found on GCB?

**Comment by dionjwa** [comment]
I'm also experiencing this problem, running `cloud-build-local` on two different (unrelated) local projects. I'll see an error message like this:
```
ERROR: build step 0 "docker/compose:1.22.0" failed: exit status 137
Error response from daemon: removal of container metadata is already in progress
2019/01/13 14:10:18 Build finished with ERROR status
```

Diagnosing, fixing, and updating cloud builds is a time-consuming process, being able to run locally is a win that saves significant time, being able to run concurrent local builds would save even more time.

**Comment by bbzg** [comment]
Would love to see progress on this. We too run multiple parallel builds from gradle. Works perfectly for remote cloud build, but local is a pain to wait for them to build and push in sequence...

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
