### ISSUE TITLE
support Windows

### ISSUE THREAD

**Issue by cilerler** [GoogleCloudPlatform/cloud-build-local#72]
Please support Windows

**Comment by zaucy** [comment]
At the very least document that it's not supposed on windows. Came here because I am getting this error while trying to install:
```
ERROR: (gcloud.components.install) The following components are unknown [cloud-build-local].
```

**Comment by Philmod** [comment]
Hi,

It's mentionned in the [readme](https://github.com/GoogleCloudPlatform/cloud-build-local#limitations).

If you feel adventurous, feel free to submit a PR :-)

**Comment by zaucy** [comment]
Ah, it's even mentioned on the documentation here: https://cloud.google.com/cloud-build/docs/build-debug-locally

Excuse my ignorance. :)

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
