### ISSUE TITLE
Privileged mode is incompatible with user namespaces

### ISSUE THREAD

**Issue by wminshew** [GoogleCloudPlatform/cloud-build-local#73]
Hi -- wanted to leave a comment that users with `userns-remap` enabled will have to add the flag `--userns=host` for docker to run properly with `--privileged` (discussed here: https://docs.docker.com/engine/security/userns-remap/#user-namespace-known-limitations)

For posterity:
in Build/build.go in func dockerRunArgs I added the following two lines (after "--privileged" on line 1195):
```
...
// Run in privileged mode per discussion in b/31267381.                                                                                                              
"--privileged",                                                                                                                                                      
// Add userns=host in case dockerd has userns enabled                                                                                                                
"--userns=host",
)
...
```

this fixed my initial error

thank you!

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
