### ISSUE TITLE
Error when "=" is included in substitution string

### ISSUE THREAD

**Issue by kenta-polyglot** [GoogleCloudPlatform/cloud-build-local#78]
Hi

When "=" is included in substitution string, error reported like below:
```
2018/08/27 17:43:33 Error parsing substitutions flag: The substitution key value pair is not valid:
```

I think `keyValue := strings.Split(s, "=")` is the cause.

- common/common.go
```
        for _, s := range list {
		keyValue := strings.Split(s, "=") # here
		if len(keyValue) != 2 {
			return substitutionsMap, fmt.Errorf("The substitution key value pair is not valid: %s", s)
		}
		substitutionsMap[strings.TrimSpace(keyValue[0])] = strings.TrimSpace(keyValue[1])
	}
```

**Comment by codrienne** [comment]
Hi,

Thanks for catching that! I'll file a bug internally. Out of curiousity, when are you needing the `=` character in a substitution?

Reproduction:
```
#cloudbuild.yaml
steps:
- name: 'ubuntu'
  args: ['echo', '$_FOO']
```

```
$ cloud-build-local --config=cloudbuild.yaml --dryrun=false --substitutions=_FOO="1+1=2" .`
2018/08/27 10:22:16 Error parsing substitutions flag: The substitution key value pair is not valid: _FOO=1+1=2
```

Best,
Edrienne

**Comment by kenta-polyglot** [comment]
Hi @codrienne,

> Out of curiousity, when are you needing the = character in a substitution?

It's a base64 encoded secret strings.

Of course we avoid uploading secret strings to GitHub or other version control system.
But we are allowed to set them on CloudBuild substitute strings.

Because if someone can see it, they have permission to sign-in GCP.
So we don't consider It's unsecure.

Thanks,
Kenta

**Comment by barefoot-coders-cicd** [comment]
He folks. Is there any update on this issue?

**Comment by bskinny** [comment]
Hi folks, is there any update on this issue?

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
