### ISSUE TITLE
Gets stuck during build

### ISSUE THREAD

**Issue by volkanunsal** [GoogleCloudPlatform/cloud-build-local#79]
I'm testing this out, and right off the bat it's getting into a bad state and does not ever get out of it. Here is my CLI:

```
➜  webapp (ruby-2.3.7) git:(master) ✗ cloud-build-local --config $BUILD_CONFIG --dryrun=false .
2018/08/29 13:30:08 Warning: there are left over step containers from a previous build, cleaning them.

➜  webapp (ruby-2.3.7) git:(master) ✗ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                          PORTS               NAMES
cbf5e3cf2088        busybox             "sh"                About a minute ago   Exited (0) About a minute ago                       cloudbuild_vol_d454aed9-e3dd-4f0b-86bb-c58a3fd6337d-helper
➜  webapp (ruby-2.3.7) git:(master) ✗  docker rm -f cbf5e3cf2088


```

As you can see, it tries to clear exited containers but this one container cannot be removed from the looks of it.

**Comment by volkanunsal** [comment]
It seems to be alive. I guess when I didn't see any progress for a while I got impatient. It'd be cool to see a progress bar...

**Comment by volkanunsal** [comment]
Actually, the container processes get stuck pretty often, even after I stop the build. I have to restart Docker pretty regularly. I wonder if there is anything that can be done about it.

**Comment by volkanunsal** [comment]
Maybe this is related 

```
2018/08/29 14:02:30 Warning: The client docker version installed (18.06.0-ce) is different from the one used in GCB (17.12.0-ce)
```

**Comment by dmcguire81** [comment]
This is a blocker for adoption on my team.

**Comment by iiro** [comment]
This happens repeatedly...? For me - it took very long (multiple minutes) in the first-ever run - but not since then... Still monitoring this though... A progress bar would have helped yes - as I also thought it was completely stuck.

**Comment by joshfermin** [comment]
I've found that restarting the docker daemon helps.

**Comment by govindrai** [comment]
Something about the cloud build local tool causes the docker daemon to break. I don't have the first clue as to what it would be, but it gets pretty annoying.. Have to end up restarting the daemon..

**Comment by imjared** [comment]
@govindrai how are you determining that the daemon broke? i'm facing what feels like a similar issue

**Comment by joelbernstein** [comment]
cloud-build-local seems very unresilient to previous runs being exited with ^C.

```
➜  lernpartner-monorepo-take5 cloud-build-local --config deploy/cloudbuild.yaml --substitutions=BRANCH_NAME=master,SHORT_SHA=0952e4 -dryrun=false -write-workspace=/tmp/workspace .
2019/10/02 15:25:06 Warning: there are left over step containers from a previous build, cleaning them.

[hangs forever here]
```

I found the only reliable fix is to stop it, `docker container prune`, and that usually seems to clear out whatever's blocking. Not much of a fix though.

Why is cloud-build-local so incredibly poor?

**Comment by timorkal** [comment]
Hi, any progress here, I am encountering this also very often...

**Comment by p3nnst8r** [comment]
Any idea on a resolution to this? I am not sure if it is WSL(2) on Windows causing the issue, but after I start, it just hangs and never stops, then I can't prune the container until I restart Docker.

**Comment by larsenv** [comment]
Becky G

**Comment by Lizzardd** [comment]
I'm having the same issue, its very unreliable. Sometimes it will work, sometimes a docker restart will solve the issue, other times I have to clean all images and restart almost everything.
Very difficult to see what's going on at all and very frustrating as it worked fine a while ago and something changed. Either a WSL upgrade or SDK change. 

I've tried upgrading to the latest versions of everything involved and still nothing

The docker container prune, isn't working it also just seems to hang

**Comment by Lizzardd** [comment]
cloud-build-local --config=cloudbuild-test.yaml --dryrun=false --substitutions _NODE_VERSION=10 .
2021/02/26 09:39:25 Warning: The server docker version installed (20.10.2) is different from the one used in GCB (19.03.8)
2021/02/26 09:39:25 Warning: The client docker version installed (20.10.2) is different from the one used in GCB (19.03.8)
Using default tag: latest
latest: Pulling from cloud-builders/metadata
ba3557a56b15: Pull complete
62f33247aa42: Pull complete
Digest: sha256:536670bb921ecc24b77665ec66e43588c7bb3e0f477f15a5414fdca06aae18a8
Status: Downloaded newer image for gcr.io/cloud-builders/metadata:latest
gcr.io/cloud-builders/metadata:latest
2021/02/26 10:29:25 Started spoofed metadata server
2021/02/26 10:29:25 Build id = localbuild_beb860d9-3e55-43f5-a0d6-5c10a5dd42d6
2021/02/26 10:29:25 status changed to "BUILD"



Nearly an hour to actually start doing any builds
I'm on a 500mb fibre line so even if it was downloading images, no ways it should take this long

**Comment by akauppi** [comment]
>The docker container prune, isn't working it also just seems to hang

If I restart Docker before running it, it seems to work.

Still, maybe the `#1` Issue Google should look into, regarding this tool.

**Comment by Lizzardd** [comment]
Given how long I've had issues with this, I don't think Google is even looking into the use of this tool
Its not available for the windows SDK and it doesn't seem to work with WSL
Real pitty as it would make life much easier when testing changes

**Comment by Friedrich42** [comment]
I have the same issue 
```bash
❯  cloud-build-local --config=cloudbuild.yaml --dryrun=false --push=false .
2021/06/08 19:17:48 Warning: there are left over step volumes from a previous build, cleaning it.
2021/06/08 19:17:48 Warning: The server docker version installed (20.10.7) is different from the one used in GCB (19.03.8)
2021/06/08 19:17:48 Warning: The client docker version installed (20.10.7) is different from the one used in GCB (19.03.8)
```

**Comment by Lizzardd** [comment]
It seem if you leave it to run it does eventually go through, but it takes ages compared to how quick it used to be

**Comment by nguyenxndaidev** [comment]
So annoying issue:

```
# cloud-build-local --dryrun=false .
2021/08/12 12:11:46 Warning: there are left over step containers from a previous build, cleaning them.
2021/08/12 12:11:46 Warning: there are left over step volumes from a previous build, cleaning it.
2021/08/12 12:11:46 Warning: The server docker version installed (20.10.7) is different from the one used in GCB (19.03.8)
2021/08/12 12:11:46 Warning: The client docker version installed (19.03.11) is different from the one used in GCB (19.03.8)
```

**Comment by Lizzardd** [comment]
Would be great its Google or Docker would address this issue as testing locally is currently not even an option with these issues

**Comment by akauppi** [comment]
@Lizzardd I agree. However, since I went for `gcloud builds submit` instead of `cloud-build-local` on my workflow, I haven’t looked back. It’s not local, but it feels like it.

If nothing is going to happen, stating so would also be a good deed from Google. Ie. pulling the plug on this repo instead of keeping it in the permanent limbo.

**Comment by Lizzardd** [comment]
I'll check it out

**Comment by TheKingzCode** [comment]
> I've found that restarting the docker daemon helps.

How are you restarting the docker daemon?

**Comment by joelbernstein** [comment]
However you usually do on your platform? How to use Docker is probably out
of scope here!

**Comment by Lizzardd** [comment]
For some reason I decided to try this all out again, on a new project we are setting up
To my amazement local cloud builds are working perfectly with docker desktop now. Not sure what's changes but so far its working for me

**Comment by joelbernstein** [comment]
It always worked perfectly right up until it hung and required manual
intervention. If the tool didn't work _at all_ we wouldn't be bothering to
comment on it

**Comment by joelbernstein** [comment]
I experienced this only on Mac OS.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
