### ISSUE TITLE
Substitutions cannot contain commas

### ISSUE THREAD

**Issue by christian-roggia** [GoogleCloudPlatform/cloud-build-local#82]
Currently, we are facing the following issue at our company: We need to define a base DN for our LDAP connection and this DN is different in DEV, STAGE, and PROD and therefore needs to be configurable.

The issue is that LDAP DN has a format similar to `DC=example,DC=com` and this format confuses the Cloud Builder which tries to break down the string into more substitution, returning the error `Error merging substitutions and validating build: substitution key "DC" does not respect format "^_[A-Z0-9_]+$" and is not an overridable built-in substitutions`.

It seems that currently it is not possible to escape this string in any way. This scenario is also likely to appear in other situations where having a comma in the substitutions is necessary.

Our current workaround is to encode in base64 the DN, but again this is not a clean solution to the issue.

**Comment by christian-roggia** [comment]
A valid solution would probably be to improve the parsing of the substitutions flag or to allow escaping of characters.

**Comment by codrienne** [comment]
Thanks for the feature request; we are tracking this internally.

**Comment by luukvhoudt** [comment]
+1 on allowing character escaping.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
