### ISSUE TITLE
--write-workspace does not work for directories outside of $PWD

### ISSUE THREAD

**Issue by mschwart** [GoogleCloudPlatform/cloud-build-local#83]
```shell
# Works: creates $PWD/workspace
cloud-build-local --dryrun=false --write-workspace=. .
# Works: creates $PWD/subdir/workspace
cloud-build-local --dryrun=false --write-workspace=subdir .
# Runs fine but either no workspace directory is created in ".." or it is not populated.
# I've seen both behaviours.
cloud-build-local --dryrun=false --write-workspace=.. .
```
Expected: write-workspace should write to any given directory or print an error if not possible.
Observed: build completes but workspace is not created or not populated.

**Comment by matihost** [comment]
It also does not work when "-bind-mount-source" is passed - which make sense as the workspace is mounted directly.
However some warning message that the flag is ignored would be nice to have.

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
