### ISSUE TITLE
local cloud build error: Error updating token in metadata server: Got HTTP 403 from spoofed metadata

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-build-local#86]
I tried running the local cloud build to debug a build issue and I repeatedly get the following error while it is trying to pull a docker image (the build just continuously posts the following error):

Error updating token in metadata server: Got HTTP 403 from spoofed metadata

**Comment by bendory** [comment]
This is most likely a failure to set header "Metadata-Flavor: Google" in the http headers; see
https://cloud.google.com/compute/docs/storing-retrieving-metadata#querying

We're preparing a fix that will relax the newly pedantic enforcement of this requirement and expect that to be released in the coming hours.

**Comment by bendory** [comment]
Sorry, I should have followed up here... closing as resolved. If you see this resurface, please re-open.
