### ISSUE TITLE
Recommended way for container networking in cloud build?

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-build-local#87]
I'm setting up an integration test on cloud build and am starting a set of containers that I'd like to be able to communicate.  I used an approach similar to the one recommended here: https://stackoverflow.com/a/52400857/8115327

Basically I am using build steps executing docker-compose to create the containers and add them to the cloudbuild network.  I was expecting to be able to address them via their container names but they are not finding each other.

What is the recommended way to have containers able to communicate to each other via container name?

**Comment by ggprod** [comment]
oops.. will put this question in the standard cloud build project

**Comment by eddiemonge** [comment]
Can you link to that issue you created?

**Comment by ggprod** [comment]
Yes, I had posted this on a Google Cloud Insider's forum:
https://groups.google.com/forum/#!searchin/google-cloud-insiders/mark$20pevec%7Csort:date/google-cloud-insiders/thR6DM6YQZo/-rDcZZm0DwAJ

From there, I was pointed to this example repo:
https://github.com/Philmod/gcb-docker-compose

**Comment by northtree** [comment]
@ggprod Have you solved this issue yet?

**Comment by ggprod** [comment]
@northtree yes, using the same approach as in the example https://github.com/Philmod/gcb-docker-compose (placing all the test containers on the cloudbuild docker bridge network)
