### ISSUE TITLE
/workspace can not be re-mounted in inner docker calls

### ISSUE THREAD

**Issue by dmcguire81** [GoogleCloudPlatform/cloud-build-local#91]
Working with `cloud-build-local` to try to debug a fairly complex, 8-step cloud build specification, I ran into a strange behavior that's hard to describe. It involves reasoning about nested docker containers invoking other containers, and re-mounting volumes that were mounted in the outer containers. Unfortunately, I can't share the file that would probably make a great test case for you with the following steps:

* 'gcr.io/cloud-builders/gsutil'
* 'gcr.io/cloud-builders/docker'
* 'docker/compose:1.23.2'
* 'docker/compose:1.23.2'
* 'gcr.io/cloud-builders/gsutil'
* 'docker/compose:1.23.2'
* 'gcr.io/cloud-builders/docker'
* 'docker/compose:1.23.2'

Instead, I spent some time trying to distill down the essential problem, and that resulted in [this public gist](https://gist.github.com/dmcguire81/c9e8c20248ec1f7f6cc656fbae124d4d). The `README.md` file is in the gist because it's used in the repro case, but it has the description. Essentially, it comes down to the following working correctly in cloud build, but not `cloud-build-local` (assuming you run both from the downloaded gist folder):

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace:/project', 'ubuntu', 'stat', '/project/README.md']
```

Please let me know if there's any other information I can provide.

**Comment by lyspj** [comment]
I'm suffering from this problem too. One of my build steps launches a docker-compose container, and the containers launched by that docker-compose cannot access /workspace.

@dmcguire81 the gist that you created is very informative and helpful - thank you!

Does anyone from the Google Cloud Build team have any thoughts on this?

**Comment by langri-sha** [comment]
Mostly using `docker-compose` as a single source of truth for building images, for the time being until Kaniko introduces support https://github.com/GoogleContainerTools/kaniko/issues/309.

If you are in a similar situation, you might be able to move the `compose` steps into a separate configuration and use a dedicated trigger. Then you can resume using `cloud-build-local` for running containers in the configurations you'd like to reproduce and debug locally.

**Comment by Syleron** [comment]
I'd like to point out that this isn't explicitly clear anywhere and took a sometime to come across this issue before finding the gist that resolved this for me. Could we see some documentation on this?

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
