### ISSUE TITLE
Feature request: run a single step with a -step flag

### ISSUE THREAD

**Issue by dmcguire81** [GoogleCloudPlatform/cloud-build-local#92]
Debugging long scripts would be made more ergonomic with a `-step` flag that allowed you to specify the step number to run. I appreciate that the equivalent functionality doesn't exist in the hosted service, but, for the debugging use case, it would be great to inspect interim state to do a bit of manual testing of invariants. Thanks for your consideration!

**Comment by codrienne** [comment]
Thanks for the FR!

**Comment by bendory** [comment]
Close Issue as part of archive process; please see [notice of archive status](https://github.com/GoogleCloudPlatform/cloud-build-local/blob/master/README.md#this-project-is-archived-and-no-longer-supported-developed-or-maintained).
