### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by eddiemonge** [GoogleCloudPlatform/cloud-build-local#97]
How do I join the Slack channel?

**Comment by codrienne** [comment]
Join the #cloudbuild channel in the Google Cloud Community Slack.  https://googlecloud-community.slack.com/

It's documented here: https://cloud.google.com/cloud-build/docs/getting-support

**Comment by eddiemonge** [comment]
Thanks. That link should be added to the Readme's Support section

**Comment by codrienne** [comment]
Good point. The next localbuilder release should have that change.
